import { Community } from '../types/community';
import { Trip } from '../types/trip';

export const DEMO_COMMUNITIES: Community[] = [
  {
    id: 'comm-001', name: 'LC Club KSA',
    description: 'مجتمع ملاك تويوتا لاند كروزر في السعودية. نخطط رحلات برية وسياحية بشكل دوري.',
    car_model: 'Toyota Land Cruiser',
    cover_image_url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800',
    visibility: 'public', invite_code: 'LC-KSA-2026',
    rules: '• الاحترام المتبادل بين الأعضاء\n• الالتزام بالمواعيد في الرحلات\n• عدم نشر محتوى غير لائق\n• الالتزام بقيادة آمنة',
    member_count: 234, created_by: 'demo-user', created_at: '2026-01-15T10:00:00Z', updated_at: '2026-09-20T15:30:00Z',
  },
  {
    id: 'comm-002', name: 'باترول السعودي',
    description: 'مجموعة لمحبي نيسان باترول. رحلات برية في جميع مناطق المملكة.',
    car_model: 'Nissan Patrol',
    cover_image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800',
    visibility: 'public', invite_code: 'PATROL-SA',
    rules: '• ممنوع السباقات الخطيرة\n• المساعدة بين الأعضاء\n• الإبلاغ عن المخالفات',
    member_count: 189, created_by: 'demo-user', created_at: '2026-02-20T10:00:00Z', updated_at: '2026-09-18T12:00:00Z',
  },
  {
    id: 'comm-003', name: 'يوتا أوف رود',
    description: 'مجتمع Jeep Wrangler السعودي. متخصص في الطرق الوعرة والتطعيس.',
    car_model: 'Jeep Wrangler',
    cover_image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
    visibility: 'public', invite_code: 'JEEP-OFFROAD',
    rules: '• السلامة أولاً\n• عدم المخاطرة الفردية\n• احترام البيئة',
    member_count: 156, created_by: 'demo-user', created_at: '2026-03-10T10:00:00Z', updated_at: '2026-09-15T09:00:00Z',
  },
  {
    id: 'comm-004', name: 'هيلكس التمشيطة',
    description: 'رحبات برية بسيارات تويوتا هيلكس. تخييم وتطعيس في شمال المملكة.',
    car_model: 'Toyota Hilux',
    cover_image_url: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800',
    visibility: 'public', invite_code: 'HILUX-TAM',
    rules: '• روح الفريق\n• ترك المكان نظيفاً\n• المساعدة في الشدات',
    member_count: 98, created_by: 'demo-user', created_at: '2026-04-05T10:00:00Z', updated_at: '2026-09-10T14:00:00Z',
  },
  {
    id: 'comm-005', name: 'جي كليبس الرياض',
    description: 'لقاءات أسبوعية لملاك Jeep Grand Cherokee في الرياض. تعارف ورحلات قصيرة.',
    car_model: 'Jeep Grand Cherokee',
    cover_image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    visibility: 'private', invite_code: 'GCLUB-RYD',
    rules: '• حضور لقاء واحد على الأقل شهرياً\n• المشاركة في الرحلات الاختيارية',
    member_count: 56, created_by: 'demo-user', created_at: '2026-05-12T10:00:00Z', updated_at: '2026-09-08T11:00:00Z',
  },
  {
    id: 'comm-006', name: 'سيدان السعودي',
    description: 'مجتمع محبي السيارات السيدان. رحلات سياحية وتناول الطعام معاً.',
    car_model: 'Various Sedans',
    cover_image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    visibility: 'public', invite_code: 'SEDAN-SA',
    rules: '• ممنوع السباقات\n• الالتزام بالمواعيد',
    member_count: 312, created_by: 'demo-user', created_at: '2026-01-01T10:00:00Z', updated_at: '2026-09-22T08:00:00Z',
  },
];

export const DEMO_TRIPS: Trip[] = [
  {
    id: 'trip-001', community_id: 'comm-001', title: 'رحلة وادي ديسي',
    description: 'رحلة برية في وادي ديسي تبوك. تطعيس وتخييم تحت النجوم.',
    category: 'offroad', estimated_cost: 350, cost_currency: 'SAR',
    destination: { name: 'وادي ديسي، تبوك', lat: 29.5, lng: 35.5 },
    meeting_point: { name: 'محطة بنزين الفيصلية، تبوك', lat: 28.4, lng: 36.5 },
    route_stops: [
      { name: 'محطة وقود الفيصلية', type: 'fuel', lat: 28.5, lng: 36.4 },
      { name: 'استراحة وادي ديسي', type: 'rest_area', lat: 29.0, lng: 36.0 },
    ],
    date: '2026-10-05', departure_time: '06:00', estimated_return: '18:00',
    participant_limit: 15, current_participants: 12,
    status: 'published',
    itinerary: '6:00 AM — الاجتماع في محطة الفيصلية\n7:00 AM — الانطلاق نحو وادي ديسي\n9:00 AM — الوصول والتطعيس\n12:00 PM — الغداء\n3:00 PM — استراحة قهوة\n5:00 PM — العودة',
    preparation_checklist: ['إطارات احتياطية', 'وقود كافي', 'ماء وطعام', 'حبل شد', 'GPS أو خرائط'],
    created_by: 'user-001', created_at: '2026-09-15T10:00:00Z', updated_at: '2026-09-20T15:30:00Z',
    community: { id: 'comm-001', name: 'LC Club KSA', car_model: 'Toyota Land Cruiser' },
  },
  {
    id: 'trip-002', community_id: 'comm-001', title: 'تخييم في مزارع الشفا',
    description: 'رحلة تخييم في مزارع الشفا الطائف. أجواء باردة وطبيعة خلابة.',
    category: 'camping', estimated_cost: 200, cost_currency: 'SAR',
    destination: { name: 'مزارع الشفا، الطائف', lat: 21.3, lng: 40.3 },
    meeting_point: { name: 'مجمع العرب، جدة', lat: 21.5, lng: 39.2 },
    route_stops: [
      { name: 'استراحة الكعكية', type: 'restaurant', lat: 21.4, lng: 39.8 },
      { name: 'محطة الشفا', type: 'fuel', lat: 21.3, lng: 40.2 },
    ],
    date: '2026-10-12', departure_time: '14:00', estimated_return: '10:00',
    participant_limit: 10, current_participants: 8,
    status: 'published',
    itinerary: '2:00 PM — الاجتماع في مجمع العرب\n4:00 PM — الوصول للمخيم\n5:00 PM — نصب الخيام\n7:00 PM — العشاء والجلسة',
    preparation_checklist: ['خيمة', 'نوميات', 'فحم وشواية', 'ملابس دافئة', 'مصابيح'],
    created_by: 'user-001', created_at: '2026-09-18T10:00:00Z', updated_at: '2026-09-22T12:00:00Z',
    community: { id: 'comm-001', name: 'LC Club KSA', car_model: 'Toyota Land Cruiser' },
  },
  {
    id: 'trip-003', community_id: 'comm-002', title: 'لقاء جدة باترول',
    description: 'لقاء أسبوعي لملاك الباترول في كورنيش جدة. تعارف ومشاوي.',
    category: 'city_meetup', estimated_cost: 50, cost_currency: 'SAR',
    destination: { name: 'كورنيش جدة', lat: 21.7, lng: 39.1 },
    meeting_point: { name: 'كورنيش جدة - شارع الأندلس', lat: 21.7, lng: 39.1 },
    route_stops: [],
    date: '2026-09-26', departure_time: '19:00', estimated_return: '22:00',
    participant_limit: 30, current_participants: 25,
    status: 'published',
    itinerary: '7:00 PM — الاجتماع والتعارف\n8:00 PM — المشوي\n9:00 PM — جولة بالكورنيش',
    preparation_checklist: ['سيارتك نظيفة', 'موقف مسبق'],
    created_by: 'user-004', created_at: '2026-09-20T10:00:00Z', updated_at: '2026-09-22T08:00:00Z',
    community: { id: 'comm-002', name: 'باترول السعودي', car_model: 'Nissan Patrol' },
  },
  {
    id: 'trip-004', community_id: 'comm-003', title: 'تطعيس النفود الكبير',
    description: 'رحلة تطعيس في صحراء النفود الكبير. مغامرة حقيقية للجيب الشيروكي.',
    category: 'offroad', estimated_cost: 500, cost_currency: 'SAR',
    destination: { name: 'صحراء النفود، حائل', lat: 27.5, lng: 41.7 },
    meeting_point: { name: 'محطة دواء، حائل', lat: 27.5, lng: 41.7 },
    route_stops: [{ name: 'محطة دواء', type: 'fuel', lat: 27.5, lng: 41.7 }],
    date: '2026-11-02', departure_time: '05:00', estimated_return: '20:00',
    participant_limit: 12, current_participants: 5,
    status: 'published',
    itinerary: '5:00 AM — الانطلاق من حائل\n7:00 AM — الوصول للنفود\n8:00 AM — بدء التطعيس\n12:00 PM — غداء\n4:00 PM — استراحة\n6:00 PM — العودة',
    preparation_checklist: ['GPS', 'إطارات رملية', 'وقود إضافي', 'طعام لمدة يوم', 'حبل شد', 'جيك عالي', 'مفك إطارات'],
    created_by: 'user-001', created_at: '2026-09-10T10:00:00Z', updated_at: '2026-09-21T14:00:00Z',
    community: { id: 'comm-003', name: 'يوتا أوف رود', car_model: 'Jeep Wrangler' },
  },
];
